# Generated by Django 5.1.1 on 2024-09-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salearticles',
            name='categorie',
        ),
    ]
