# Generated by Django 5.1.1 on 2024-09-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_alter_salearticles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salearticles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
