# Generated by Django 5.1.1 on 2024-09-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_alter_salearticles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salearticles',
            name='user',
            field=models.CharField(),
        ),
    ]
