# Generated by Django 5.1.1 on 2024-09-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsp',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
