# Generated by Django 5.1.1 on 2024-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsp_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsp',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
