# Generated by Django 5.1.1 on 2024-09-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsp',
            name='description',
        ),
    ]
