# Generated by Django 5.1.1 on 2024-09-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productsp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsp',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='productsP',
        ),
    ]
